'use client';
import React from 'react';
import { motion } from 'framer-motion';
import styles from './introducingHero.module.scss';
import Button from '@/components/button';

export default function IntroducingHero() {
    return (
        <div className={styles.introducingHero}>
            <div className={styles.leftRightAlignment}>
                <motion.h1
                    initial={{ opacity: 0, y: 40 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.85, ease: [0.16, 1, 0.3, 1] }}
                >
                    partner with yume <br />  prime earn up to 80%
                    <span> commission rebate share </span>
                </motion.h1>
                <motion.div
                    initial={{ opacity: 0, y: 30 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.8, delay: 0.2, ease: [0.16, 1, 0.3, 1] }}
                >
                    <p>
                        Refer traders to Yume Prime and earn a share of the commission generated by every trade they place for as long as they trade. No caps, no
                        complicated tiers to unlock, and payouts you can withdraw instantly.
                    </p>
                    <motion.div
                        whileHover={{ scale: 1.02, y: -2 }}
                        whileTap={{ scale: 0.98 }}
                        transition={{ duration: 0.2 }}
                    >
                        <Button text="Become an Introducing Broker" />
                    </motion.div>
                </motion.div>
            </div>
        </div>
    );
}

